fast_hash: fast_hash.c
	gcc -o fast_hash fast_hash.c

test_fast_hash: test_fast_hash.c
	gcc -o test_fast_hash test_fast_hash.c

test_fast_hash_speed: test_fast_hash_speed.c
	gcc -o test_fast_hash_speed test_fast_hash_speed.c

test_map_hash_speed: test_map_hash_speed.c
	gcc -o test_map_hash_speed test_map_hash_speed.c

test_old_hash_speed: test_old_hash_speed.c
	gcc -o test_old_hash_speed test_old_hash_speed.c

test_empty_loop: test_empty_loop.c
	gcc -o test_empty_loop test_empty_loop.c

clean:
	rm fast_hash test_fast_hash test_fast_hash_speed test_map_hash_speed test_old_hash_speed test_empty_loop
